# Generated by Django 3.1.3 on 2020-12-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='center_x',
        ),
        migrations.RemoveField(
            model_name='client',
            name='center_y',
        ),
        migrations.RemoveField(
            model_name='client',
            name='options_x',
        ),
        migrations.RemoveField(
            model_name='client',
            name='options_y',
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_x', models.IntegerField(default=0)),
                ('center_y', models.IntegerField(default=0)),
                ('kind', models.CharField(blank=True, choices=[('left', 'Left Button'), ('right', 'Right Button'), ('down', 'Down Button'), ('up', 'Up Button'), ('start', 'Start Button'), ('pause', 'Pause Button')], max_length=32, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='core.client')),
            ],
        ),
        migrations.AlterField(
            model_name='touch',
            name='button',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touches', to='core.button'),
        ),
    ]
