# Generated by Django 3.1.3 on 2020-12-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201220_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='size',
            field=models.IntegerField(default=35),
        ),
    ]
