# Generated by Django 3.1.3 on 2021-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_button_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='encode_background_color',
            field=models.CharField(default='89_133_234', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='encode_shade',
            field=models.CharField(default='0_8_15_0.2', max_length=430),
        ),
        migrations.AddField(
            model_name='client',
            name='shade_direction',
            field=models.CharField(default='LEFT', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='transparency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
