# Generated by Django 3.1.3 on 2021-12-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211218_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='border_size',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=10),
        ),
    ]
